#!/bin/bash
# Composio usage guide (installation already complete)

echo '========================================='
echo 'COMPOSIO USAGE GUIDE'
echo '========================================='
echo ''
echo 'Composio is already installed at:'
echo '  Binary: /sandbox/.composio/composio'
echo '  Wrapper: /sandbox/bin/composio'
echo '  Version: 0.2.22'
echo ''
echo '========================================='
echo 'OPTION 1: Add to PATH (recommended)'
echo '========================================='
echo 'export PATH=/sandbox/bin:$PATH'
echo ''
echo 'Then test:'
echo '  composio --version'
echo '  composio search "github" --limit 1'
echo ''
echo '========================================='
echo 'OPTION 2: Use full paths'
echo '========================================='
echo 'Direct binary:'
echo '  /sandbox/.composio/composio [command]'
echo ''
echo 'Via wrapper:'
echo '  /sandbox/bin/composio [command]'
echo ''
echo '========================================='
echo 'EXAMPLE COMMANDS'
echo '========================================='
echo '1. Search for tools:'
echo '   composio search "send github notification"'
echo ''
echo '2. Link GitHub account:'
echo '   composio link github'
echo ''
echo '3. Execute a tool:'
echo '   composio execute GITHUB_CREATE_AN_ISSUE \\'
echo '     -d '\''{"owner":"Jackclaw-hub","repo":"jacknemo-platform","title":"Bug"}'\'''
echo ''
echo '========================================='
echo 'TROUBLESHOOTING'
echo '========================================='
echo 'If "composio: command not found":'
echo '  1. Check if PATH includes /sandbox/bin'
echo '  2. Use full path: /sandbox/bin/composio'
echo '  3. Verify file exists: ls -la /sandbox/bin/composio'
echo ''
echo 'For detailed report see: composio_installation_report.md'