/**
 * Startup Radar — Mock Catalog
 * All catalog content lives here on window.SR_DATA.
 * Edit freely to tune the radar demo.
 */

window.SR_DATA = {

  // ── Funding signals ───────────────────────────────────────────────────────
  funding: [
    {
      id: 'f1',
      title: 'EU Horizon Seed Grant — Deep Tech',
      org: 'European Innovation Council',
      summary: 'Non-dilutive grant up to €150k for science-based startups at ideation or early MVP stage.',
      stages: ['idea', 'mvp'],
      sectors: ['tech', 'health', 'climate'],
      geo: 'regional',
      regions: ['EU'],
      deadline: '2026-06-30',
      url: '#',
    },
    {
      id: 'f2',
      title: 'Founders First Syndicate',
      org: 'Founders First',
      summary: 'Angel syndicate investing €25k–€100k in pre-seed B2B SaaS. Rolling applications.',
      stages: ['mvp', 'early-revenue'],
      sectors: ['saas', 'tech', 'b2b'],
      geo: 'remote',
      regions: [],
      deadline: null,
      url: '#',
    },
    {
      id: 'f3',
      title: 'Berlin Innovation Fund',
      org: 'Investitionsbank Berlin',
      summary: 'Regional co-investment program for Berlin-based startups. Up to €500k at seed stage.',
      stages: ['mvp', 'early-revenue'],
      sectors: ['tech', 'creative', 'climate'],
      geo: 'regional',
      regions: ['Berlin', 'DE'],
      deadline: '2026-09-01',
      url: '#',
    },
    {
      id: 'f4',
      title: 'Climate Accelerator Grant',
      org: 'GreenFoundry',
      summary: 'Non-dilutive €50k grant + 3-month program for climate-tech founders. Open globally.',
      stages: ['idea', 'mvp'],
      sectors: ['climate', 'hardware', 'tech'],
      geo: 'remote',
      regions: [],
      deadline: '2026-05-15',
      url: '#',
    },
    {
      id: 'f5',
      title: 'Women-Led Ventures Fund',
      org: 'Launchpad Europe',
      summary: 'Dedicated pre-seed fund (€30k–€150k) for women-founded startups across any sector.',
      stages: ['idea', 'mvp', 'early-revenue'],
      sectors: [],  // all sectors
      geo: 'regional',
      regions: ['EU'],
      deadline: null,
      url: '#',
    },
    {
      id: 'f6',
      title: 'Health Innovation Seed',
      org: 'BioHub Capital',
      summary: 'Seed investment €50k–€200k for digital health, medtech, and biotech startups.',
      stages: ['mvp', 'early-revenue'],
      sectors: ['health'],
      geo: 'remote',
      regions: [],
      deadline: '2026-07-31',
      url: '#',
    },
    {
      id: 'f7',
      title: 'Creative Industries Micro-Grant',
      org: 'Creative Europe Program',
      summary: 'Micro-grants €5k–€25k for creative, media, and cultural startups at idea stage.',
      stages: ['idea'],
      sectors: ['creative', 'media'],
      geo: 'regional',
      regions: ['EU'],
      deadline: '2026-04-30',
      url: '#',
    },
    {
      id: 'f8',
      title: 'Open Source Collective Grant',
      org: 'OSC Foundation',
      summary: 'Recurring grant for open-source SaaS projects. Any stage, any region.',
      stages: ['idea', 'mvp', 'early-revenue', 'growth'],
      sectors: ['saas', 'tech'],
      geo: 'remote',
      regions: [],
      deadline: null,
      url: '#',
    },
    {
      id: 'f9',
      title: 'AgriTech Accelerator',
      org: 'Rural Ventures',
      summary: '€75k grant + mentorship for agri-tech startups solving food chain inefficiencies.',
      stages: ['idea', 'mvp'],
      sectors: ['agritech', 'climate', 'hardware'],
      geo: 'regional',
      regions: ['EU', 'DE', 'NL'],
      deadline: '2026-08-01',
      url: '#',
    },
    {
      id: 'f10',
      title: 'Revenue-Based Financing — SME',
      org: 'CapitalFlow',
      summary: 'Non-dilutive RBF from €20k to €500k for early-revenue stage. No equity taken.',
      stages: ['early-revenue', 'growth'],
      sectors: [],
      geo: 'remote',
      regions: [],
      deadline: null,
      url: '#',
    },
  ],

  // ── Equipment & space listings ────────────────────────────────────────────
  equipment: [
    {
      id: 'e1',
      title: 'Professional Video Studio — Full Day',
      owner: 'Studio Hub Berlin',
      ownerType: 'hub',
      summary: '4K camera, lighting rig, teleprompter, green screen. Ideal for pitch videos or product demos.',
      tags: ['idea', 'mvp', 'early-revenue', 'video', 'media', 'creative'],
      geo: 'regional',
      city: 'Berlin',
      dailyRate: 280,
      hourlyRate: null,
      url: '#',
    },
    {
      id: 'e2',
      title: 'Shared Lab Space — Biotech Bench',
      owner: 'BioHub Munich',
      ownerType: 'hub',
      summary: 'Certified wet-lab benches, fridge/freezer access, centrifuge. Per-session booking.',
      tags: ['mvp', 'early-revenue', 'health', 'hardware'],
      geo: 'regional',
      city: 'Munich',
      dailyRate: 150,
      hourlyRate: 30,
      url: '#',
    },
    {
      id: 'e3',
      title: 'DJI Mavic 3 Pro — Drone Kit',
      owner: 'Lukas Meier (solo)',
      ownerType: 'solo',
      summary: 'Drone + spare batteries + ND filters. Perfect for promotional or product content.',
      tags: ['idea', 'mvp', 'creative', 'media'],
      geo: 'regional',
      city: 'Hamburg',
      dailyRate: 95,
      hourlyRate: null,
      url: '#',
    },
    {
      id: 'e4',
      title: '3D Printer Farm — Prototyping',
      owner: 'Maker Hub Frankfurt',
      ownerType: 'hub',
      summary: '6× FDM + 2× resin printers. Book single units or the full farm for batch prototyping.',
      tags: ['idea', 'mvp', 'hardware', 'tech'],
      geo: 'regional',
      city: 'Frankfurt',
      dailyRate: 80,
      hourlyRate: 15,
      url: '#',
    },
    {
      id: 'e5',
      title: 'MacBook Pro M3 Max — Short-term rental',
      owner: 'TechShare Amsterdam',
      ownerType: 'solo',
      summary: 'M3 Max, 64GB RAM, 2TB SSD. Ideal for ML/AI inference, video editing, or dev sprints.',
      tags: ['idea', 'mvp', 'early-revenue', 'tech', 'saas'],
      geo: 'remote',
      city: null,
      dailyRate: 45,
      hourlyRate: null,
      url: '#',
    },
    {
      id: 'e6',
      title: 'Private Meeting Rooms — Flexible',
      owner: 'Co.up Coworking',
      ownerType: 'hub',
      summary: '4–12 person meeting rooms in Berlin Mitte. Whiteboard, AV, coffee included.',
      tags: ['idea', 'mvp', 'early-revenue', 'growth'],
      geo: 'regional',
      city: 'Berlin',
      dailyRate: null,
      hourlyRate: 35,
      url: '#',
    },
    {
      id: 'e7',
      title: 'Audio Recording Suite',
      owner: 'Soundspace Hamburg',
      ownerType: 'hub',
      summary: 'Professional vocal booth and mixing suite. Great for podcast launches or audio branding.',
      tags: ['idea', 'mvp', 'creative', 'media'],
      geo: 'regional',
      city: 'Hamburg',
      dailyRate: 180,
      hourlyRate: 40,
      url: '#',
    },
    {
      id: 'e8',
      title: 'EV Fleet — Test & Demo',
      owner: 'GreenMobility Labs',
      ownerType: 'hub',
      summary: '3 electric vehicles available for test drives, field demos, or logistics pilots.',
      tags: ['mvp', 'early-revenue', 'climate', 'hardware'],
      geo: 'regional',
      city: 'Stuttgart',
      dailyRate: 120,
      hourlyRate: null,
      url: '#',
    },
    {
      id: 'e9',
      title: 'Thermal Imaging Camera',
      owner: 'Hans Koch (solo)',
      ownerType: 'solo',
      summary: 'FLIR industrial thermal camera for hardware testing, building audits, or R&D demos.',
      tags: ['mvp', 'hardware', 'climate', 'tech'],
      geo: 'remote',
      city: null,
      dailyRate: 75,
      hourlyRate: null,
      url: '#',
    },
    {
      id: 'e10',
      title: 'Event Space — 80 pax',
      owner: 'Betahaus Berlin',
      ownerType: 'hub',
      summary: 'Open-plan event space for demo days, launch events, or community meetups. AV + catering options.',
      tags: ['early-revenue', 'growth'],
      geo: 'regional',
      city: 'Berlin',
      dailyRate: 600,
      hourlyRate: 120,
      url: '#',
    },
  ],

  // ── Service listings ──────────────────────────────────────────────────────
  services: [
    {
      id: 's1',
      title: 'Startup Legal Pack — Company Formation + IP',
      provider: 'Recht & Gründen',
      summary: 'Fixed-fee package: GmbH registration, co-founder agreement, IP assignment, NDA template.',
      stages: ['idea', 'mvp'],
      sectors: [],
      starterFriendly: true,
      geo: 'remote',
      city: null,
      fromPrice: 1200,
      url: '#',
    },
    {
      id: 's2',
      title: 'Brand Identity Sprint — 5 Days',
      provider: 'Feldform Studio',
      summary: 'Logo, colour palette, typography, icon set, and brand guidelines. Delivered in 5 business days.',
      stages: ['idea', 'mvp', 'early-revenue'],
      sectors: [],
      starterFriendly: true,
      geo: 'remote',
      city: null,
      fromPrice: 1800,
      url: '#',
    },
    {
      id: 's3',
      title: 'MVP Development — React + Node.js',
      provider: 'Codecraft Agency',
      summary: '4-week sprint to build your MVP. Fixed scope, fixed price. React frontend + REST API.',
      stages: ['idea', 'mvp'],
      sectors: ['saas', 'tech', 'b2b'],
      starterFriendly: true,
      geo: 'remote',
      city: null,
      fromPrice: 8000,
      url: '#',
    },
    {
      id: 's4',
      title: 'SEO & Content Strategy',
      provider: 'GrowthLab',
      summary: 'Keyword research, on-page SEO audit, 3-month content calendar, and 4 articles included.',
      stages: ['early-revenue', 'growth'],
      sectors: [],
      starterFriendly: true,
      geo: 'remote',
      city: null,
      fromPrice: 900,
      url: '#',
    },
    {
      id: 's5',
      title: 'Financial Modelling — Investor Ready',
      provider: 'NumberStack',
      summary: '3-statement model, unit economics, scenario analysis, and pitch-deck-ready charts.',
      stages: ['mvp', 'early-revenue'],
      sectors: [],
      starterFriendly: true,
      geo: 'remote',
      city: null,
      fromPrice: 1500,
      url: '#',
    },
    {
      id: 's6',
      title: 'UI/UX Design for SaaS',
      provider: 'Pixel & Flow',
      summary: 'User research, wireframes, hi-fi Figma prototype, and design system starter kit.',
      stages: ['idea', 'mvp'],
      sectors: ['saas', 'tech'],
      starterFriendly: true,
      geo: 'remote',
      city: null,
      fromPrice: 2400,
      url: '#',
    },
    {
      id: 's7',
      title: 'Pitch Deck Coaching',
      provider: 'Investor Lens',
      summary: '3-session coaching program: structure, story, slides, and live pitch practice with an ex-VC.',
      stages: ['idea', 'mvp', 'early-revenue'],
      sectors: [],
      starterFriendly: true,
      geo: 'remote',
      city: null,
      fromPrice: 600,
      url: '#',
    },
    {
      id: 's8',
      title: 'Data Engineering — Analytics Stack',
      provider: 'DataForm',
      summary: 'Set up your data warehouse (BigQuery/Snowflake), ETL pipelines, and BI dashboard.',
      stages: ['early-revenue', 'growth'],
      sectors: ['saas', 'tech'],
      starterFriendly: false,
      geo: 'remote',
      city: null,
      fromPrice: 5000,
      url: '#',
    },
    {
      id: 's9',
      title: 'Social Media Starter Pack',
      provider: 'Digital Sprout',
      summary: '30 days of content creation + scheduling for LinkedIn, Instagram, and X. Includes strategy doc.',
      stages: ['idea', 'mvp', 'early-revenue'],
      sectors: [],
      starterFriendly: true,
      geo: 'remote',
      city: null,
      fromPrice: 750,
      url: '#',
    },
    {
      id: 's10',
      title: 'Regulatory & Compliance Audit — EU',
      provider: 'ComplianceFirst',
      summary: 'GDPR compliance review, AI Act readiness check, and data processing documentation.',
      stages: ['early-revenue', 'growth'],
      sectors: ['tech', 'health', 'saas'],
      starterFriendly: false,
      geo: 'regional',
      city: null,
      fromPrice: 2200,
      url: '#',
    },
  ],

  // ── Admin mock users ──────────────────────────────────────────────────────
  adminUsers: [
    { id: 'u1', name: 'Lena Baumann',   role: 'Founder',   stage: 'MVP',           sector: 'SaaS',    joined: '2026-03-15', status: 'active' },
    { id: 'u2', name: 'Marco Russo',    role: 'Founder',   stage: 'Idea',          sector: 'Climate', joined: '2026-03-20', status: 'active' },
    { id: 'u3', name: 'Studio Hub Berlin', role: 'Equipment', stage: '—',          sector: 'Space',   joined: '2026-02-10', status: 'verified' },
    { id: 'u4', name: 'Feldform Studio',role: 'Service',   stage: '—',             sector: 'Design',  joined: '2026-01-05', status: 'verified' },
    { id: 'u5', name: 'Amira El-Amin',  role: 'Founder',   stage: 'Early Revenue', sector: 'Health',  joined: '2026-03-28', status: 'active' },
    { id: 'u6', name: 'Lukas Meier',    role: 'Equipment', stage: '—',             sector: 'Media',   joined: '2026-04-01', status: 'pending' },
    { id: 'u7', name: 'Codecraft Agency',role: 'Service',  stage: '—',             sector: 'Dev',     joined: '2026-02-14', status: 'verified' },
    { id: 'u8', name: 'David Nkosi',    role: 'Founder',   stage: 'MVP',           sector: 'AgriTech',joined: '2026-04-02', status: 'active' },
    { id: 'u9', name: 'Hans Koch',      role: 'Equipment', stage: '—',             sector: 'Hardware',joined: '2026-04-05', status: 'pending' },
    { id: 'u10', name: 'GrowthLab',     role: 'Service',   stage: '—',             sector: 'Growth',  joined: '2026-03-01', status: 'flagged' },
  ],
};
