require("dotenv").config();
const express = require("express");
const healthRouter = require("./routes/health");
const authRouter = require("./routes/auth");
const app = express();
app.use(express.json());
app.use("/api", healthRouter);
app.use("/api", authRouter);
app.use((_req, res) => res.status(404).json({ error: "Not found" }));
const PORT = process.env.PORT || 3000;
if (require.main === module) app.listen(PORT, () => process.stdout.write("Server running on port " + PORT + "\n"));
module.exports = app;
